In [8]:
import numpy as np
print("---Store Student Marks in a 1D Array---")
mark=np.array([92,83,95])
print(mark)

---Store Student Marks in a 1D Array---
[92 83 95]


In [10]:
print("---Store Employee Monthly Sales Data---")
employee=np.array([[45000,46000,45500],[50000,55000,49000]])
print(employee)

---Store Employee Monthly Sales Data---
[[45000 46000 45500]
 [50000 55000 49000]]


In [11]:
print("---Initialize an Empty Attendance Sheet---")
sheet=np.zeros((2,3))
print(sheet)

---Initialize an Empty Attendance Sheet---
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print("---Analyze Dataset Properties---")
print(employee.shape)
print(employee.ndim)
print(employee.size)
print(employee.dtype)

---Analyze Dataset Properties---
(2, 3)
2
6
int64


In [21]:
print("---Retrieve a Specific Record---")
print(employee[0,2])

---Retrieve a Specific Record---
45500


In [22]:
print("---Display the sales of all employees for the second month---")
print(employee[:,1])

---Display the sales of all employees for the second month---
[46000 55000]


In [23]:
print("---Display all monthly sales of the second employee---")
print(employee[1,:])

---Display all monthly sales of the second employee---
[50000 55000 49000]


In [24]:
print("---Extract the first two rows and first two columns from the dataset---")
print(employee[0:2,0:2])


---Extract the first two rows and first two columns from the dataset---
[[45000 46000]
 [50000 55000]]


In [26]:
print("---Initialize a New Parking Lot---")
lot=np.ones([2,3])
print(lot)

---Initialize a New Parking Lot---
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
print("---Student Roll Number Matrix---")
Roll=np.eye(3)
print(Roll)

---Student Roll Number Matrix---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print("---Bus Departure Timings---")
time=np.arange(1,20,2)
print(time)

---Bus Departure Timings---
[ 1  3  5  7  9 11 13 15 17 19]


In [33]:
print("---Temperature Monitoring---")
tem=np.linspace(1,3,6)
print(tem)

---Temperature Monitoring---
[1.  1.4 1.8 2.2 2.6 3. ]
