In [51]:
import numpy as np
mileage = np.array([650,900,1100,1400,1700,2100,2400,2700,3200,4000,5500]).reshape(-1, 1)
car_price = np.array([120000,170000,210000,260000,310000,380000,430000,490000,560000,680000,830000])
print("mileage(Km):")
print(house_size)
print("\ncar_price($):")
print(car_price)

mileage(Km):
[[ 650]
 [ 900]
 [1100]
 [1400]
 [1700]
 [2100]
 [2400]
 [2700]
 [3200]
 [4000]
 [5500]]

car_price($):
[120000 170000 210000 260000 310000 380000 430000 490000 560000 680000
 830000]


In [52]:
import pandas as pd
df = pd.DataFrame({'Mileage(KM)': mileage.flatten(), 'car_price($)': car_price})
print("Dataset:")
print(df)
print('\nDataset shape:' ,df.shape)

Dataset:
    Mileage(KM)  car_price($)
0           650        120000
1           900        170000
2          1100        210000
3          1400        260000
4          1700        310000
5          2100        380000
6          2400        430000
7          2700        490000
8          3200        560000
9          4000        680000
10         5500        830000

Dataset shape: (11, 2)


In [55]:
from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(mileage, car_price, test_size=0.3, random_state=42)
print(f"Training set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

Training set size: 7
Testing set size: 4


In [64]:
print(mileage.flatten())
print('-'*20)
print('Training Input\n',X_train)
print('-'*20)
print('Testing Input\n',X_test)

[ 650  900 1100 1400 1700 2100 2400 2700 3200 4000 5500]
--------------------
Training Input
 [[1100]
 [ 900]
 [3200]
 [1700]
 [2700]
 [1400]
 [2400]]
--------------------
Testing Input
 [[2100]
 [ 650]
 [4000]
 [5500]]


In [67]:
model = LinearRegression()   
model.fit(X_train, y_train)  
slope = model.coef_[0]       # b1 (slope)
intercept = model.intercept_ # b0 (intercept)
print(f"Equation: Car Price = {slope:.2f} × Mileage + {intercept:.2f}")
print(f"\nSlope: ₹{slope:.2f} per km")
print(f"Intercept: ₹{intercept:.2f}")


Equation: Car Price = 170.85 × Mileage + 20088.72

Slope: ₹170.85 per km
Intercept: ₹20088.72


In [68]:
y_pred_train = model.predict(X_train)  
y_pred_test = model.predict(X_test)  
new_mileage = np.array([[30000]]) 
predicted_price = model.predict(new_mileage)[0]

print(f"Predicted price for a car with 30,000 km mileage: ₹{predicted_price:,.2f}")

Predicted price for a car with 30,000 km mileage: ₹5,145,564.01
