In [23]:
import numpy as np
m1 = np.array([[78, 85], [92, 88]])
m2 = np.array([[2, 1], [1, 2]])
print("Matrix Multiplication using dot():")
print(np.dot(m1,m2))

Matrix Multiplication using dot():
[[241 248]
 [272 268]]


In [3]:
print("\nMatrix Multiplication using @:")
print(m1 @ m2)


Matrix Multiplication using @:
[[241 248]
 [272 268]]


In [24]:
print("\nTranspose of Student Marks:")
print(m1.T)


Transpose of Student Marks:
[[78 92]
 [85 88]]


In [26]:
print("Random Attendance Percentage:")
print(np.random.rand(2,3))

Random Attendance Percentage:
[[0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]


In [27]:
print("\nRandom Quiz Scores:")
print(np.random.randint(0, 10,size=(2, 3)))


Random Quiz Scores:
[[2 6 4]
 [8 6 1]]


In [10]:
print("\nRandom Performance Distribution:")
print(np.random.randn(2, 3))


Random Performance Distribution:
[[-0.46947439  0.54256004 -0.46341769]
 [-0.46572975  0.24196227 -1.91328024]]


In [28]:
classA = np.array([80, 75, 90])
classB = np.array([85, 88, 92])
print("Vertical Stack:")
print(np.vstack((classA, classB)))

Vertical Stack:
[[80 75 90]
 [85 88 92]]


In [13]:
print("\nHorizontal Stack:")
print(np.hstack((classA, classB)))


Horizontal Stack:
[80 75 90 85 88 92]


In [14]:
print("\nConcatenate:")
print(np.concatenate((classA, classB)))


Concatenate:
[80 75 90 85 88 92]


In [15]:
print("\nSplit Roll Numbers:")
print(np.split(np.arange(9), 3))


Split Roll Numbers:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [29]:
scores = np.array([65, 82, 74, 90, 56, 99, 71, 88])
print("Sorted Scores:")
print(np.sort(scores))

Sorted Scores:
[56 65 71 74 82 88 90 99]


In [18]:
print("\nOriginal Index Order:")
print(np.argsort(scores))


Original Index Order:
[4 0 6 2 1 7 3 5]


In [19]:
print("\nScores Greater Than 80:")
print(np.where(scores > 80))


Scores Greater Than 80:
(array([1, 3, 5, 7]),)


In [30]:
marks = np.array([35, 42, 55, 28, 76])
passed = marks >= 40
print("Pass Status:")
print(passed)
print("\nPassed Student Marks:")
print(marks[passed])

Pass Status:
[False  True  True False  True]

Passed Student Marks:
[42 55 76]
