In [10]:
import numpy as np
stock = np.array([120, 85, 60, 150, 95, 40, 200, 75])

print("Current Stock:")
print(stock)

print("\nTotal Products in Stock:")
print(np.sum(stock))
print("\nAverage Stock:")
print(np.mean(stock))
print("\nHighest Stock:")
print(np.max(stock))
print("\nLowest Stock:")
print(np.min(stock))
print("\nProducts Below 80 Units:")
print(stock[stock < 80])
updated_stock = np.where(stock < 80, stock + 50, stock)

print("\nUpdated Stock After Restocking:")
print(updated_stock)
print("\nTotal Stock After Restocking:")
print(np.sum(updated_stock))

Current Stock:
[120  85  60 150  95  40 200  75]

Total Products in Stock:
825

Average Stock:
103.125

Highest Stock:
200

Lowest Stock:
40

Products Below 80 Units:
[60 40 75]

Updated Stock After Restocking:
[120  85 110 150  95  90 200 125]

Total Stock After Restocking:
975
