In [32]:
print("---Reshape the given List---")
import numpy as np
products=np.array([134,453,354,754,643,747])
reshape=products.reshape(2,3)
print(reshape)

---Reshape the given List---
[[134 453 354]
 [754 643 747]]


In [37]:
print("---use flatten & ravel---")
val=np.array([[547,743,637,737],[563,365,653,753]])
flat=val.flatten()
print(flat)
print("change the value")
flatt=val.flatten()
flatt[0]=638
print(flatt)
print("check orginal value")
print(flat)
print("using ravel")
ravel=val.ravel()
print(ravel)
print("change the value")
r=val.ravel()
r[1]=72
print(r)
print("check if orginal value changed permentally")
print(ravel)


---use flatten & ravel---
[547 743 637 737 563 365 653 753]
change the value
[638 743 637 737 563 365 653 753]
check orginal value
[547 743 637 737 563 365 653 753]
using ravel
[547 743 637 737 563 365 653 753]
change the value
[547  72 637 737 563 365 653 753]
check if orginal value changed permentally
[547  72 637 737 563 365 653 753]


In [34]:
print("---1D Arithmetic operations using numpy---")
val1 = np.array([120, 150, 180])
val2 = np.array([100, 140, 160])
print(val1+val2)
print(val1-val2)
print(val1*val2)
print(val1/val2)
print(val1**2)

---1D Arithmetic operations using numpy---
[220 290 340]
[20 10 20]
[12000 21000 28800]
[1.2        1.07142857 1.125     ]
[14400 22500 32400]


In [35]:
print("---2D Arithmetic operations using numpy---")
value1=np.array([[43,63,83,51],[53,78,36,74]])
value2=np.array([47,67,74,12])
print("\nadd",value1+value2)
print('\nsub',value1-value2)
print('\nmul',value1*value2)
print('\ndiv',value1/value2)

---2D Arithmetic operations using numpy---

add [[ 90 130 157  63]
 [100 145 110  86]]

sub [[ -4  -4   9  39]
 [  6  11 -38  62]]

mul [[2021 4221 6142  612]
 [2491 5226 2664  888]]

div [[0.91489362 0.94029851 1.12162162 4.25      ]
 [1.12765957 1.1641791  0.48648649 6.16666667]]


In [36]:
print("--- add column-wise @ row-wise---")
print(value1.sum(axis=0))
print(value1.sum(axis=1))

--- add column-wise @ row-wise---
[ 96 141 119 125]
[240 241]
