In [25]:
import numpy as np
class_a = np.array([[85, 90, 88],[78, 82, 80]])
class_b = np.array([[91, 87, 89],[84, 86, 83]])
print("\nClass A")
print(section_a)
print("\nClass B")
print(section_b)


Class A
[[85 90 88]
 [78 82 80]]

Class B
[[91 87 89]
 [84 86 83]]


In [26]:
print("\n--- Vertical Stack -----")
v_data = np.vstack((class_a, class_b))
print(v_data)


--- Vertical Stack -----
[[85 90 88]
 [78 82 80]
 [91 87 89]
 [84 86 83]]


In [27]:
print("\n--- Horizontal Stack -----")
h_data = np.hstack((class_a, class_b))
print(h_data)


--- Horizontal Stack -----
[[85 90 88 91 87 89]
 [78 82 80 84 86 83]]


In [28]:
print("\n----- Concatenate (Axis=0) ---")
con_data = np.concatenate((class_a, class_b), axis=0)
print(con_data)


----- Concatenate (Axis=0) ---
[[85 90 88]
 [78 82 80]
 [91 87 89]
 [84 86 83]]


In [29]:
print("\n---- Split Data ---")
split_data = np.split(con_data, 2)
print(split_data[0])


---- Split Data ---
[[85 90 88]
 [78 82 80]]


In [30]:
print(split_data[1])

[[91 87 89]
 [84 86 83]]


In [31]:
print("\n----- Save Data -----")
np.save("student_marks.npy", con_data)
print("Data Saved Successfully")


----- Save Data -----
Data Saved Successfully


In [32]:
print("\n--- Load Data ---")
load = np.load("student_marks.npy")
print(load)


--- Load Data ---
[[85 90 88]
 [78 82 80]
 [91 87 89]
 [84 86 83]]
